global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prepaid-meter-api"
    static_configs:
      - targets: ["172.17.0.1:30081"]
    metrics_path: /metrics

  - job_name: "prepaid-meter-api-local"
    static_configs:
      - targets: ["172.17.0.1:8014"]
    metrics_path: /metrics
